### ISSUE TITLE
Employee management page

### ISSUE THREAD

**Issue by Danila-Sergeev** [antonymofyou/HireEmployeesVue#120]

**Comment by antonymofyou** [comment]
Замечания:
1. На широком экране нужно на ширину сделать как в откликах. Если получится, вообще в одну строчку попробовать данные уместить
2. id можно серым и шрифтом на пару единиц меньше
3. удаление сотрудника делаем только из карточки
4. нужно сделать получения айди сотрудника по ссылке. Получается вставляем ссылку, рядом кнопку проверить, и далее после проверки будет отображаться ВК айди сотрудника. 
5. После редактирования ВК айди сотрудника не меняем

**Comment by antonymofyou** [comment]
1. Непонятно, почему макс ширина 600. в других местах же 700
2. Я просил сделать удаление сотрудника только внутри страницы редактирования
3. При подгрузке ВК айди у тебя нигде не появляется прогрессбар. Ошибка тоже должна появляться НЕ в попапе
4. Страница редактирования -> Редактирование сотрудника (заголовок)
5. Почему при изменении поля ВК срабатывает кнопка сохранения. Что-то не так.
