### ISSUE TITLE
feat: CandidateComments

### ISSUE THREAD

**Issue by Clockmerk** [antonymofyou/HireEmployeesVue#22]
Создание тестового роута получения комментариев к кандидату и отклику - in progress
Написание базовой структуры - in progress
Проработка запроса получения данных - in progress

**Comment by RainbowIsPerfect** [comment]
Создание страницы комментариев и компонентов для нее - done
Функционал по работе с комментариями - done
Рефакторинг - in progress

**Comment by RainbowIsPerfect** [comment]
Иконки на кнопках - done
Рефакторинг - done
Скрытие кнопок редактирования на комментариях других юзеров - in progress

**Comment by RainbowIsPerfect** [comment]
Скрытие кнопок редактирования на комментариях других юзеров - done

**Comment by Clockmerk** [comment]
Дополнения и исправления:

- Исправление запросов при редактировании комментариев
- Правка элементов
- Правка стилей
- Рефакторинг

**Comment by Clockmerk** [comment]
Дополнения и исправления:

- Правка состояния компонента
- Написание базовой структуры компонента ответов на вопросы

**Comment by Clockmerk** [comment]
Дополнения и исправления:

- Правка верстки
- Написание базовой структуры компонента информации о кандидате

**Comment by Clockmerk** [comment]
Дополнения и исправления:

- Правка использования методов
- Добавление метода получения информации к отклику
- Правка структуры
- Добавление/оптимизация элементов
